// Country to timezone mapping for auto-detection
export const countries = [
  { code: "US", name: "United States", timezone: "America/New_York" },
  { code: "GB", name: "United Kingdom", timezone: "Europe/London" },
  { code: "CA", name: "Canada", timezone: "America/Toronto" },
  { code: "AU", name: "Australia", timezone: "Australia/Sydney" },
  { code: "IN", name: "India", timezone: "Asia/Kolkata" },
  { code: "DE", name: "Germany", timezone: "Europe/Berlin" },
  { code: "FR", name: "France", timezone: "Europe/Paris" },
  { code: "JP", name: "Japan", timezone: "Asia/Tokyo" },
  { code: "CN", name: "China", timezone: "Asia/Shanghai" },
  { code: "BR", name: "Brazil", timezone: "America/Sao_Paulo" },
  { code: "MX", name: "Mexico", timezone: "America/Mexico_City" },
  { code: "KR", name: "South Korea", timezone: "Asia/Seoul" },
  { code: "IT", name: "Italy", timezone: "Europe/Rome" },
  { code: "ES", name: "Spain", timezone: "Europe/Madrid" },
  { code: "NL", name: "Netherlands", timezone: "Europe/Amsterdam" },
  { code: "SE", name: "Sweden", timezone: "Europe/Stockholm" },
  { code: "NO", name: "Norway", timezone: "Europe/Oslo" },
  { code: "DK", name: "Denmark", timezone: "Europe/Copenhagen" },
  { code: "FI", name: "Finland", timezone: "Europe/Helsinki" },
  { code: "PL", name: "Poland", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", timezone: "Europe/Lisbon" },
  { code: "RU", name: "Russia", timezone: "Europe/Moscow" },
  { code: "ZA", name: "South Africa", timezone: "Africa/Johannesburg" },
  { code: "AE", name: "UAE", timezone: "Asia/Dubai" },
  { code: "SA", name: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { code: "SG", name: "Singapore", timezone: "Asia/Singapore" },
  { code: "HK", name: "Hong Kong", timezone: "Asia/Hong_Kong" },
  { code: "TW", name: "Taiwan", timezone: "Asia/Taipei" },
  { code: "TH", name: "Thailand", timezone: "Asia/Bangkok" },
  { code: "ID", name: "Indonesia", timezone: "Asia/Jakarta" },
  { code: "PH", name: "Philippines", timezone: "Asia/Manila" },
  { code: "MY", name: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { code: "NZ", name: "New Zealand", timezone: "Pacific/Auckland" },
  { code: "AR", name: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { code: "CL", name: "Chile", timezone: "America/Santiago" },
  { code: "CO", name: "Colombia", timezone: "America/Bogota" },
  { code: "EG", name: "Egypt", timezone: "Africa/Cairo" },
  { code: "NG", name: "Nigeria", timezone: "Africa/Lagos" },
  { code: "KE", name: "Kenya", timezone: "Africa/Nairobi" },
  { code: "IL", name: "Israel", timezone: "Asia/Jerusalem" },
  { code: "TR", name: "Turkey", timezone: "Europe/Istanbul" },
  { code: "PK", name: "Pakistan", timezone: "Asia/Karachi" },
  { code: "BD", name: "Bangladesh", timezone: "Asia/Dhaka" },
  { code: "VN", name: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { code: "IE", name: "Ireland", timezone: "Europe/Dublin" },
  { code: "CH", name: "Switzerland", timezone: "Europe/Zurich" },
  { code: "AT", name: "Austria", timezone: "Europe/Vienna" },
  { code: "BE", name: "Belgium", timezone: "Europe/Brussels" },
  { code: "CZ", name: "Czech Republic", timezone: "Europe/Prague" },
  { code: "RO", name: "Romania", timezone: "Europe/Bucharest" },
  { code: "GR", name: "Greece", timezone: "Europe/Athens" },
  { code: "UA", name: "Ukraine", timezone: "Europe/Kyiv" },
  { code: "LK", name: "Sri Lanka", timezone: "Asia/Colombo" },
  { code: "NP", name: "Nepal", timezone: "Asia/Kathmandu" },
].sort((a, b) => a.name.localeCompare(b.name));

export const timezoneOptions = [
  { value: "America/New_York", label: "Eastern Time (US)" },
  { value: "America/Chicago", label: "Central Time (US)" },
  { value: "America/Denver", label: "Mountain Time (US)" },
  { value: "America/Los_Angeles", label: "Pacific Time (US)" },
  { value: "America/Toronto", label: "Toronto (EST)" },
  { value: "America/Sao_Paulo", label: "São Paulo (BRT)" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires (ART)" },
  { value: "America/Mexico_City", label: "Mexico City (CST)" },
  { value: "America/Bogota", label: "Bogotá (COT)" },
  { value: "America/Santiago", label: "Santiago (CLT)" },
  { value: "Europe/London", label: "London (GMT)" },
  { value: "Europe/Paris", label: "Paris (CET)" },
  { value: "Europe/Berlin", label: "Berlin (CET)" },
  { value: "Europe/Madrid", label: "Madrid (CET)" },
  { value: "Europe/Rome", label: "Rome (CET)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (CET)" },
  { value: "Europe/Stockholm", label: "Stockholm (CET)" },
  { value: "Europe/Moscow", label: "Moscow (MSK)" },
  { value: "Europe/Istanbul", label: "Istanbul (TRT)" },
  { value: "Europe/Kyiv", label: "Kyiv (EET)" },
  { value: "Europe/Athens", label: "Athens (EET)" },
  { value: "Europe/Bucharest", label: "Bucharest (EET)" },
  { value: "Europe/Helsinki", label: "Helsinki (EET)" },
  { value: "Europe/Warsaw", label: "Warsaw (CET)" },
  { value: "Europe/Prague", label: "Prague (CET)" },
  { value: "Europe/Vienna", label: "Vienna (CET)" },
  { value: "Europe/Brussels", label: "Brussels (CET)" },
  { value: "Europe/Zurich", label: "Zurich (CET)" },
  { value: "Europe/Dublin", label: "Dublin (GMT)" },
  { value: "Europe/Lisbon", label: "Lisbon (WET)" },
  { value: "Europe/Oslo", label: "Oslo (CET)" },
  { value: "Europe/Copenhagen", label: "Copenhagen (CET)" },
  { value: "Asia/Kolkata", label: "India (IST)" },
  { value: "Asia/Tokyo", label: "Tokyo (JST)" },
  { value: "Asia/Shanghai", label: "Shanghai (CST)" },
  { value: "Asia/Seoul", label: "Seoul (KST)" },
  { value: "Asia/Singapore", label: "Singapore (SGT)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (HKT)" },
  { value: "Asia/Taipei", label: "Taipei (CST)" },
  { value: "Asia/Bangkok", label: "Bangkok (ICT)" },
  { value: "Asia/Jakarta", label: "Jakarta (WIB)" },
  { value: "Asia/Manila", label: "Manila (PHT)" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (MYT)" },
  { value: "Asia/Dubai", label: "Dubai (GST)" },
  { value: "Asia/Riyadh", label: "Riyadh (AST)" },
  { value: "Asia/Karachi", label: "Karachi (PKT)" },
  { value: "Asia/Dhaka", label: "Dhaka (BST)" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh (ICT)" },
  { value: "Asia/Jerusalem", label: "Jerusalem (IST)" },
  { value: "Asia/Colombo", label: "Colombo (IST)" },
  { value: "Asia/Kathmandu", label: "Kathmandu (NPT)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (SAST)" },
  { value: "Africa/Cairo", label: "Cairo (EET)" },
  { value: "Africa/Lagos", label: "Lagos (WAT)" },
  { value: "Africa/Nairobi", label: "Nairobi (EAT)" },
  { value: "Australia/Sydney", label: "Sydney (AEST)" },
  { value: "Pacific/Auckland", label: "Auckland (NZST)" },
];

export function getTimezoneForCountry(countryCode: string): string | null {
  const country = countries.find((c) => c.code === countryCode);
  return country?.timezone ?? null;
}
